// <auto-generated />
using System;
using DietApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20260906121509_AddBeerDays")]
    partial class AddBeerDays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DietApi.Domain.Aggregates.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Met")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchName");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.BeerDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId", "Date")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("BeerDays");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.DietAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Threshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DietAchievements");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.DietPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.EatingTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EatingTips");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.ExerciseDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId", "Date")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("ExerciseDays");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.FoodLibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchName");

                    b.ToTable("FoodLibraryItems");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.LoggedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId", "Date")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("LoggedDays");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.DietPlan", b =>
                {
                    b.OwnsOne("DietApi.Domain.ValueObjects.NutritionTargets", "Targets", b1 =>
                        {
                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Calories")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TargetCalories");

                            b1.Property<decimal?>("CarbsG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetCarbsG");

                            b1.Property<decimal?>("FatG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetFatG");

                            b1.Property<decimal?>("ProteinG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetProteinG");

                            b1.HasKey("DietPlanId");

                            b1.ToTable("DietPlans");

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsMany("DietApi.Domain.Entities.ExerciseShortcut", "ExerciseShortcuts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ActivityTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Position")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("DietPlanId", "Position");

                            b1.HasIndex("DietPlanId", "ActivityTypeId", "DurationMinutes")
                                .IsUnique();

                            b1.ToTable("ExerciseShortcuts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsMany("DietApi.Domain.Entities.UnlockedAchievement", "UnlockedAchievements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DietAchievementId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("EarnedOn")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DietPlanId", "DietAchievementId")
                                .IsUnique();

                            b1.ToTable("UnlockedAchievements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsMany("DietApi.Domain.Entities.WeightReading", "WeightReadings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(5, 2)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DietPlanId", "Date")
                                .IsUnique();

                            b1.ToTable("WeightReadings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsOne("DietApi.Domain.ValueObjects.BodyMetrics", "BodyMetrics", b1 =>
                        {
                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Age")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Age");

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(5, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("HeightCm");

                            b1.Property<string>("Sex")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Sex");

                            b1.HasKey("DietPlanId");

                            b1.ToTable("DietPlans");

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.Navigation("BodyMetrics")
                        .IsRequired();

                    b.Navigation("ExerciseShortcuts");

                    b.Navigation("Targets")
                        .IsRequired();

                    b.Navigation("UnlockedAchievements");

                    b.Navigation("WeightReadings");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.ExerciseDay", b =>
                {
                    b.OwnsMany("DietApi.Domain.Entities.ExerciseEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ActivityName")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ActivityTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EstimatedKcal")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ExerciseDayId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Met")
                                .HasPrecision(4, 1)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ExerciseDayId");

                            b1.ToTable("ExerciseEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExerciseDayId");
                        });

                    b.OwnsOne("DietApi.Domain.ValueObjects.ExerciseTotals", "Totals", b1 =>
                        {
                            b1.Property<Guid>("ExerciseDayId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Kilocalories")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TotalKilocalories");

                            b1.Property<int>("Minutes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TotalMinutes");

                            b1.HasKey("ExerciseDayId");

                            b1.ToTable("ExerciseDays");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseDayId");
                        });

                    b.Navigation("Entries");

                    b.Navigation("Totals")
                        .IsRequired();
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.FoodLibraryItem", b =>
                {
                    b.OwnsMany("DietApi.Domain.Entities.ServingSize", "ServingSizes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FoodLibraryItemId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("GramWeight")
                                .HasPrecision(7, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("FoodLibraryItemId");

                            b1.ToTable("ServingSizes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FoodLibraryItemId");

                            b1.OwnsOne("DietApi.Domain.ValueObjects.NutritionValues", "Nutrition", b2 =>
                                {
                                    b2.Property<Guid>("ServingSizeId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Calories")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("Calories");

                                    b2.Property<decimal>("CarbsG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CarbsG");

                                    b2.Property<decimal>("FatG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FatG");

                                    b2.Property<decimal>("ProteinG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ProteinG");

                                    b2.HasKey("ServingSizeId");

                                    b2.ToTable("ServingSizes");

                                    b2.WithOwner()
                                        .HasForeignKey("ServingSizeId");
                                });

                            b1.Navigation("Nutrition")
                                .IsRequired();
                        });

                    b.Navigation("ServingSizes");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.LoggedDay", b =>
                {
                    b.OwnsOne("DietApi.Domain.ValueObjects.NutritionTargets", "TargetSnapshot", b1 =>
                        {
                            b1.Property<Guid>("LoggedDayId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Calories")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TargetCalories");

                            b1.Property<decimal?>("CarbsG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetCarbsG");

                            b1.Property<decimal?>("FatG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetFatG");

                            b1.Property<decimal?>("ProteinG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetProteinG");

                            b1.HasKey("LoggedDayId");

                            b1.ToTable("LoggedDays");

                            b1.WithOwner()
                                .HasForeignKey("LoggedDayId");
                        });

                    b.OwnsOne("DietApi.Domain.ValueObjects.NutritionValues", "Totals", b1 =>
                        {
                            b1.Property<Guid>("LoggedDayId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Calories")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TotalCalories");

                            b1.Property<decimal>("CarbsG")
                                .HasPrecision(7, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalCarbsG");

                            b1.Property<decimal>("FatG")
                                .HasPrecision(7, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalFatG");

                            b1.Property<decimal>("ProteinG")
                                .HasPrecision(7, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalProteinG");

                            b1.HasKey("LoggedDayId");

                            b1.ToTable("LoggedDays");

                            b1.WithOwner()
                                .HasForeignKey("LoggedDayId");
                        });

                    b.OwnsMany("DietApi.Domain.Entities.FoodEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FoodLibraryItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FoodName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("LoggedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("LoggedDayId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MealType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(6, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServingLabel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ServingSizeId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("LoggedDayId");

                            b1.ToTable("FoodEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LoggedDayId");

                            b1.OwnsOne("DietApi.Domain.ValueObjects.NutritionValues", "Nutrition", b2 =>
                                {
                                    b2.Property<Guid>("FoodEntryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Calories")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("Calories");

                                    b2.Property<decimal>("CarbsG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CarbsG");

                                    b2.Property<decimal>("FatG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FatG");

                                    b2.Property<decimal>("ProteinG")
                                        .HasPrecision(6, 1)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ProteinG");

                                    b2.HasKey("FoodEntryId");

                                    b2.ToTable("FoodEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("FoodEntryId");
                                });

                            b1.Navigation("Nutrition")
                                .IsRequired();
                        });

                    b.Navigation("Entries");

                    b.Navigation("TargetSnapshot")
                        .IsRequired();

                    b.Navigation("Totals")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
