// <auto-generated />
using System;
using DietApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20260902044514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DietApi.Domain.Aggregates.DietPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("DietApi.Domain.Aggregates.DietPlan", b =>
                {
                    b.OwnsMany("DietApi.Domain.Entities.WeightReading", "WeightReadings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(5, 2)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DietPlanId", "Date")
                                .IsUnique();

                            b1.ToTable("WeightReadings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsOne("DietApi.Domain.ValueObjects.BodyMetrics", "BodyMetrics", b1 =>
                        {
                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Age")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Age");

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(5, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("HeightCm");

                            b1.Property<string>("Sex")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Sex");

                            b1.HasKey("DietPlanId");

                            b1.ToTable("DietPlans");

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.OwnsOne("DietApi.Domain.ValueObjects.NutritionTargets", "Targets", b1 =>
                        {
                            b1.Property<Guid>("DietPlanId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Calories")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TargetCalories");

                            b1.Property<decimal?>("CarbsG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetCarbsG");

                            b1.Property<decimal?>("FatG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetFatG");

                            b1.Property<decimal?>("ProteinG")
                                .HasPrecision(6, 1)
                                .HasColumnType("TEXT")
                                .HasColumnName("TargetProteinG");

                            b1.HasKey("DietPlanId");

                            b1.ToTable("DietPlans");

                            b1.WithOwner()
                                .HasForeignKey("DietPlanId");
                        });

                    b.Navigation("BodyMetrics")
                        .IsRequired();

                    b.Navigation("Targets")
                        .IsRequired();

                    b.Navigation("WeightReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
